### ISSUE TITLE
Support installation an RubyMine EAP builds

### ISSUE THREAD

**Issue by nirvdrum** [vitallium/intellij-plugin-ruby-lsp#56]
I've been running the 2024.3 EAPs in order to test bug fixes I've submitted upstream. Due to the version bounds specified on this plugin, version 0.0.3 [can be installed](https://plugins.jetbrains.com/plugin/24413-ruby-lsp/versions) but not anything released afterwards. Assuming it wouldn't create a major support headache, it'd be great if the upper bound could be relaxed. Unfortunately, this is a case where setting the upper bound doesn't block installation of the LSP plugin on the EAP builds; it just means all EAP users will end up installing an old version of the plugin.

**Comment by vitallium** [comment]
Hi, I think this is doable. Let me relax the `pluginUntilBuild` property to allow installing Ruby LSP in EAP builds.

**Comment by vitallium** [comment]
Added in https://github.com/vitallium/intellij-plugin-ruby-lsp/commit/a42a49ee55a50dd798017e74e21c93741415d7fb

**Comment by vitallium** [comment]
I've sent v0.0.9 for verification. It should be available for installation in a couple of days.

**Comment by vitallium** [comment]
That was fast. v0.0.9 is available now. @nirvdrum can you please check if you can install it in the RubyMine EAP?

**Comment by vitallium** [comment]
I verified it manually and the extension is available for EAP builds.
